/**
 * LocalStack Desktop — Electron Main Process (dev reference copy)
 *
 * The authoritative source is: public/electron.js
 *
 * public/electron.js is copied to build/electron.js by CRA during the React build,
 * which is where electron-builder expects to find it.
 *
 * This file is kept so `npm start` works via `"main": "public/electron.js"` in
 * package.json — electron resolves it relative to the project root in dev.
 *
 * DO NOT edit this file. Edit public/electron.js instead.
 */
// Re-export from the authoritative source
module.exports = require('../public/electron.js');
